### ISSUE TITLE
Add "Life cycle of a code change" documentation

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/codeforlife-deploy-appengine#187]
## Task Description

Write down, in a clear concise form, the life cycle of a code change in codeforlife-deploy-appengine. That is, how code goes from a branch on your computer and through our CI/CD pipelines to being deployed on production. In codeforlife-deploy-appengine's case, this is more about what happens when you change some deployment code here.

## Acceptance Criteria

- [x] Create docs folder at the root of the repository
- [x] `life-cycle-of-a-code-change.md` in the root of the docs folder
- [ ] Update contributing guidelines with link to life-cycle-of-a-code-change.md

## Copywrite Requirements

None (although docs have to be reviewed!)

## Analytics Requirements

None
