### ISSUE TITLE
Setup Amazon SES

### ISSUE THREAD

**Issue by mariaFernando** [ocadotechnology/codeforlife-deploy-appengine#211]
## Task Description
Replace custom email backend with [Amazon SES](https://aws.amazon.com/ses/) integrated through [django-anymail](https://github.com/anymail/django-anymail) .

## Acceptance Criteria
- [x] Amazon SES is setup for the project (API key and domain) and added with django-anymail
- [x] `EMAIL_BACKEND` is updated (Portal backend removed)
- [x] Move out of the AWS SES sandbox (details [here](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html)) 

## Documentation Requirements
None.

**Comment by mrniket** [comment]
Waiting on legal approval

**Comment by faucomte97** [comment]
Waiting on DNS records update

**Comment by faucomte97** [comment]
Amazon SES has now been setup properly.
However, our AWS SES account is still in sandbox mode. Which means:
- We can only send from verified emails, and
- We can only send to verified email.

Since we will be using this to email all our current users + any new users, we obviously need to change this.

Our AWS SES account can be moved out of sandbox mode by requesting AWS to do so. It's all explained [here](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html).

However, I do not currently have permission to do so. Marking this as externally blocked as a result.

**Comment by mrniket** [comment]
Sent the request, still externally blocked
