### ISSUE TITLE
Archive Kurono 😔

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-deploy-appengine#326]
## Task Description
We need to archive Kurono so that we can build on it again in the future. 

## Acceptance Criteria
- [x] Take Kurono offline
- [x] Remove GKE from stack
- [x] Remove Agones from stack
- [x] Remove Terraform from stack

### Analytics Requirements
- [x] Remove Kurono queries from Big Query

### Copywrite Requirements
- [ ] None
